name: flutter_appauth
description: This plugin provides an abstraction around the Android and iOS AppAuth SDKs so it can be used to communicate with OAuth 2.0 and OpenID Connect providers
version: 1.0.0
homepage: https://github.com/MaikuB/flutter_appauth/tree/master/flutter_appauth

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth_platform_interface:
    git:
      url: https://github.com/qhrtech/flutter_appauth.git
      ref: v1.0.0
      path: flutter_appauth_platform_interface


flutter:
  plugin:
    platforms:
      android:
        package: io.crossingthestreams.flutterappauth
        pluginClass: FlutterAppauthPlugin
      ios:
        pluginClass: FlutterAppauthPlugin
